@baseURL = http://localhost:8000
@token = ""

###

GET {{baseURL}}/ping

###

POST {{baseURL}}/auth/users/
content-type: application/json

{
    "username": "test",
    "email": "animeshrisal99@gmail.com",
    "password": "master@123",
    "re_password": "master@123"
}
###

# @name user_login
POST {{baseURL}}/auth/jwt/create/
content-type: application/json

{
    "username": "admin",
    "password": "@nimation"
}
###

@access_token = {{user_login.response.body.access}}
@refresh_token = {{user_login.response.body.refresh}}

# @name refresh
POST {{baseURL}}/auth/jwt/refresh/
content-type: application/json

{
    "refresh": "{{refresh_token}}"
}
###

@access_token = {{user_login.response.body.access}}

# @name activate_user
POST {{baseURL}}/auth/users/activation/
content-type: application/json

{
    "uid": "MQ",
    "token": "aquo6v-cf98fd961cc0123fb41b3a4871b278a2"
}
###

# @name comment

POST {{baseURL}}/dashboard/artwork/1/comment/
content-type: application/json
Authorization: JWT {{access_token}}

{
    "comment": "This drawing sucks!"
}
###

# @name comment_list

GET {{baseURL}}/dashboard/artwork/1/comment/
content-type: application/json
Authorization: JWT {{access_token}}
###

# @name comment_delete

DELETE {{baseURL}}/dashboard/artwork/1/comment/1/
content-type: application/json
Authorization: JWT {{access_token}}
###

# @name feed

GET {{baseURL}}/dashboard/feed/
content-type: application/json
Authorization: JWT {{access_token}}
###

# @name artwork

GET {{baseURL}}/dashboard/artwork/1/
content-type: application/json
Authorization: JWT {{access_token}}
###

# @name like_artwork

POST {{baseURL}}/dashboard/artwork/1/like
content-type: application/json
Authorization: JWT {{access_token}}
###

# @name unlike_artwork

DELETE {{baseURL}}/dashboard/artwork/27/like
content-type: application/json
Authorization: JWT {{access_token}}
###


# @name follow_user

POST {{baseURL}}/dashboard/user/1/follow
content-type: application/json
Authorization: JWT {{access_token}}
###

# @name unfollow_user

DELETE {{baseURL}}/dashboard/artwork/1/follow
content-type: application/json
Authorization: JWT {{access_token}}
###

# @name User Info

GET {{baseURL}}/auth/users/me
content-type: application/json
Authorization: JWT {{access_token}}
###