# Generated by Django 3.2.6 on 2021-08-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
