# Generated by Django 3.2.6 on 2021-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pic'),
        ),
    ]
