# Generated by Django 3.2.6 on 2022-01-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='initiator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to='dashboard.user'),
            preserve_default=False,
        ),
    ]
